site_name: 化学合成实验手册
repo_url: https://github.com/biantailab/chemhandbook
repo_name: biantailab/chemhandbook
docs_dir: src
nav:
  - 首页: index.md
  - 模板: 
    - 四苄基钛: template/四苄基钛.md
  - 有机物:
    - FOX-7: organic/FOX-7/index.md
    - 甘脲: organic/甘脲/index.md
    - PETN: organic/PETN/index.md
    - TNT: organic/TNT/index.md
    - DFTHP: organic/DFTHP/index.md
    - RDX: organic/RDX/index.md
    - 1,4-DNI: organic/1,4-DNI/index.md
    - HBIW: organic/HBIW/index.md
    - 4-NI: organic/4-NI/index.md
    - DAF: organic/DAF/index.md
    - MPO: organic/MPO/index.md
    - ETN: organic/ETN/index.md
    - TMETN: organic/TMETN/index.md
  - 无机物:
    - 叠氮化银: inorganic/叠氮化银/index.md
    - 氰化钾: inorganic/氰化钾/index.md


theme:
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  favicon: https://img.icons8.com/?size=100&id=58872&format=png
  icon:
    logo: fontawesome/solid/flask-vial
    repo: fontawesome/brands/github
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  features:
    - navigation.tracking
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - navigation.footer
    - content.external_link.icon
    - navigation.top
    - navigation.expand
    - navigation.instant
  custom_dir: src/overrides

copyright: Copyright &copy; 2025 BianTai LAB <p xmlns:cc="http://creativecommons.org/ns#" ><a href="https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></p>

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/biantailab
      name: GitHub
    - icon: fontawesome/brands/x-twitter 
      link: https://x.com/biantailab
      name: X
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/sDdzdsCzN7
      name: discord
    - icon: fontawesome/solid/paper-plane
      link: https://t.me/+eCTrA4kOiCI2ZTA1
      name: Telegram
extra_javascript:
  - js/chemdraw.js
  - js/smiles-drawer.min.js
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      timezone: Asia/Shanghai
      enable_creation_date: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: smiles
          class: smiles
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

